import { CategoryProvider } from "@/contexts/category-provider";
import { QueryProvider } from "@/contexts/query-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Flex } from "next/font/google";
import "react-quill-new/dist/quill.snow.css";
import { Toaster } from "sonner";
import { getAllCategories } from "./actions/category-actions";
import "./globals.css";
// Load Geist
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Load Roboto Flex
const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-roboto-flex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getAllCategories();
  return (
    <QueryProvider>
      <html lang="en">
        <body
          className={`${robotoFlex.variable}  ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CategoryProvider initialCategory={data ?? []}>
            {children}
          </CategoryProvider>

          <Toaster />
        </body>
      </html>
    </QueryProvider>
  );
}
